### ISSUE TITLE
该装的都装了还是提示缺少运行库

### ISSUE THREAD

**Issue by cocowobo** [hironpan/TorrentFileChecker#1]
![image](https://user-images.githubusercontent.com/19485885/120077085-31c07780-c0db-11eb-8d7c-cee2ad880790.png)
![image](https://user-images.githubusercontent.com/19485885/120077093-384eef00-c0db-11eb-8d44-0b85ea6548d8.png)

**Comment by cocowobo** [comment]
原来.NET Core 3.1 Runtime是独立的呀，需要单独安装

**Comment by Akariln** [comment]
麻了，前前后后装了n个 `.NET` ，
为后来者作个提醒，看清名字，确保一致，
请下载 `.NET Desktop Runtime 3.1.30` 这个：
https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-3.1.30-windows-x64-installer
